num1 = int(input('첫 번째 숫자를 입력하세요: '))
num2 = int(input('첫 번째 숫자를 입력하세요: '))
result = num1 + num2
print(num1, '+', num2, '=', result)
result = num1 - num2
print(num1, '-', num2, '=', result)
result = num1 * num2
print(num1, '*', num2, '=', result)
result = num1 / num2
print(num1, '/', num2, '=', result)
